/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthenticatedRouteImport } from './pages/_authenticated'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AppDashboardIndexRouteImport } from './pages/_app/_dashboard/index'
import { Route as AppDashboardChar126SettingsLayoutRouteImport } from './pages/_app/_dashboard/~/settings/layout'
import { Route as AppDashboardChar126SettingsIndexRouteImport } from './pages/_app/_dashboard/~/settings/index'
import { Route as AppDashboardChar126NotificationsIndexRouteImport } from './pages/_app/_dashboard/~/notifications/index'
import { Route as AppDashboardChar126SettingsRequestsIndexRouteImport } from './pages/_app/_dashboard/~/settings/requests/index'
import { Route as AppDashboardChar126SettingsProfileIndexRouteImport } from './pages/_app/_dashboard/~/settings/profile/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardChar126SettingsLayoutRoute =
  AppDashboardChar126SettingsLayoutRouteImport.update({
    id: '/_dashboard/~/settings',
    path: '/~/settings',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppDashboardChar126SettingsIndexRoute =
  AppDashboardChar126SettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDashboardChar126SettingsLayoutRoute,
  } as any)
const AppDashboardChar126NotificationsIndexRoute =
  AppDashboardChar126NotificationsIndexRouteImport.update({
    id: '/_dashboard/~/notifications/',
    path: '/~/notifications/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppDashboardChar126SettingsRequestsIndexRoute =
  AppDashboardChar126SettingsRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AppDashboardChar126SettingsLayoutRoute,
  } as any)
const AppDashboardChar126SettingsProfileIndexRoute =
  AppDashboardChar126SettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AppDashboardChar126SettingsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/': typeof AppDashboardIndexRoute
  '/~/settings': typeof AppDashboardChar126SettingsLayoutRouteWithChildren
  '/~/notifications': typeof AppDashboardChar126NotificationsIndexRoute
  '/~/settings/': typeof AppDashboardChar126SettingsIndexRoute
  '/~/settings/profile': typeof AppDashboardChar126SettingsProfileIndexRoute
  '/~/settings/requests': typeof AppDashboardChar126SettingsRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/': typeof AppDashboardIndexRoute
  '/~/notifications': typeof AppDashboardChar126NotificationsIndexRoute
  '/~/settings': typeof AppDashboardChar126SettingsIndexRoute
  '/~/settings/profile': typeof AppDashboardChar126SettingsProfileIndexRoute
  '/~/settings/requests': typeof AppDashboardChar126SettingsRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_authenticated': typeof AuthenticatedRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/_dashboard/': typeof AppDashboardIndexRoute
  '/_app/_dashboard/~/settings': typeof AppDashboardChar126SettingsLayoutRouteWithChildren
  '/_app/_dashboard/~/notifications/': typeof AppDashboardChar126NotificationsIndexRoute
  '/_app/_dashboard/~/settings/': typeof AppDashboardChar126SettingsIndexRoute
  '/_app/_dashboard/~/settings/profile/': typeof AppDashboardChar126SettingsProfileIndexRoute
  '/_app/_dashboard/~/settings/requests/': typeof AppDashboardChar126SettingsRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/~/settings'
    | '/~/notifications'
    | '/~/settings/'
    | '/~/settings/profile'
    | '/~/settings/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/~/notifications'
    | '/~/settings'
    | '/~/settings/profile'
    | '/~/settings/requests'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/_dashboard/'
    | '/_app/_dashboard/~/settings'
    | '/_app/_dashboard/~/notifications/'
    | '/_app/_dashboard/~/settings/'
    | '/_app/_dashboard/~/settings/profile/'
    | '/_app/_dashboard/~/settings/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_dashboard/': {
      id: '/_app/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_dashboard/~/settings': {
      id: '/_app/_dashboard/~/settings'
      path: '/~/settings'
      fullPath: '/~/settings'
      preLoaderRoute: typeof AppDashboardChar126SettingsLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_dashboard/~/settings/': {
      id: '/_app/_dashboard/~/settings/'
      path: '/'
      fullPath: '/~/settings/'
      preLoaderRoute: typeof AppDashboardChar126SettingsIndexRouteImport
      parentRoute: typeof AppDashboardChar126SettingsLayoutRoute
    }
    '/_app/_dashboard/~/notifications/': {
      id: '/_app/_dashboard/~/notifications/'
      path: '/~/notifications'
      fullPath: '/~/notifications'
      preLoaderRoute: typeof AppDashboardChar126NotificationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_dashboard/~/settings/requests/': {
      id: '/_app/_dashboard/~/settings/requests/'
      path: '/requests'
      fullPath: '/~/settings/requests'
      preLoaderRoute: typeof AppDashboardChar126SettingsRequestsIndexRouteImport
      parentRoute: typeof AppDashboardChar126SettingsLayoutRoute
    }
    '/_app/_dashboard/~/settings/profile/': {
      id: '/_app/_dashboard/~/settings/profile/'
      path: '/profile'
      fullPath: '/~/settings/profile'
      preLoaderRoute: typeof AppDashboardChar126SettingsProfileIndexRouteImport
      parentRoute: typeof AppDashboardChar126SettingsLayoutRoute
    }
  }
}

interface AppDashboardChar126SettingsLayoutRouteChildren {
  AppDashboardChar126SettingsIndexRoute: typeof AppDashboardChar126SettingsIndexRoute
  AppDashboardChar126SettingsProfileIndexRoute: typeof AppDashboardChar126SettingsProfileIndexRoute
  AppDashboardChar126SettingsRequestsIndexRoute: typeof AppDashboardChar126SettingsRequestsIndexRoute
}

const AppDashboardChar126SettingsLayoutRouteChildren: AppDashboardChar126SettingsLayoutRouteChildren =
  {
    AppDashboardChar126SettingsIndexRoute:
      AppDashboardChar126SettingsIndexRoute,
    AppDashboardChar126SettingsProfileIndexRoute:
      AppDashboardChar126SettingsProfileIndexRoute,
    AppDashboardChar126SettingsRequestsIndexRoute:
      AppDashboardChar126SettingsRequestsIndexRoute,
  }

const AppDashboardChar126SettingsLayoutRouteWithChildren =
  AppDashboardChar126SettingsLayoutRoute._addFileChildren(
    AppDashboardChar126SettingsLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardChar126SettingsLayoutRoute: typeof AppDashboardChar126SettingsLayoutRouteWithChildren
  AppDashboardChar126NotificationsIndexRoute: typeof AppDashboardChar126NotificationsIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardChar126SettingsLayoutRoute:
    AppDashboardChar126SettingsLayoutRouteWithChildren,
  AppDashboardChar126NotificationsIndexRoute:
    AppDashboardChar126NotificationsIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
